### ISSUE TITLE
NFS VAAI documentation missing crucial pre-requisite information

### ISSUE THREAD

**Issue by flexdataSolutions** [NetAppDocs/ontap-tools-vmware-vsphere-10#13]
### Page URL

https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/configure/install-nfs-vaai-plug-in.html

### Page title

Install the NFS VAAI plug-in

### Summary

The information contained in this KB should be included in the product documentation: https://kb.netapp.com/on-prem/ontap/DM/VAAI/VAAI-KBs/Configure_the_correct_NFS_export_policies_for_VAAI_copy_offload

Without this extra information stuff fails, like 3rd party integrated backups, like VM deployment from templates, like Storage vMotion, etc ... 

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-jani** [comment]
@flexdataSolutions 
Thank you for contacting us with your feedback. After your inputs are researched internally, we will determine how best to address it and update the content at the earliest.

Thanks,
Jani

**Comment by netapp-jani** [comment]
@flexdataSolutions Thank you for your feedback. The link to the KB article is incorporated into the doc.
