### ISSUE TITLE
Add limits

### ISSUE THREAD

**Issue by netapp-bingen** [NetAppDocs/ontap-tools-vmware-vsphere-10#16]
### Page URL

https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/deploy/sizing-requirements.html

### Page title

Prerequisites for deploying ONTAP tools for VMware vSphere

### Summary

We mention the different sizes here (S, M, L), as well as a couple of other pages, but I don't see where we say why you would choose each size, meaning, how many hosts, datastores, VMs, and vVols each size can support.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-jani** [comment]
@netapp-bingen 
Thank you for contacting us with your feedback. After your inputs are researched internally, we will determine how best to address it and update the content at the earliest.

Thanks,
Jani

**Comment by netapp-jani** [comment]
@netapp-bingen created a JIRA https://jira.ngage.netapp.com/browse/OTVDOC-120 to track this internally. For future communication please check this JIRA and you can create a new one for any other doc updates.
