### ISSUE TITLE
Change SRM to VMware Live Site Recovery (VLSR)

### ISSUE THREAD

**Issue by jpowellgit** [NetAppDocs/ontap-tools-vmware-vsphere-10#18]
### Page URL

https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/protect/configure-on-srm-appliance.html

### Page title

Configure SRA on the SRM appliance

### Summary

SRM is no longer the name of the product from VMware. I would suggest changing this to VMware Live Site Recovery and providing the versions of both products that are supported.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-jani** [comment]
@jpowellgit 
Thank you for contacting us with your feedback. After your inputs are researched internally, we will determine how best to address it and update the content at the earliest.

Thanks,
Jani

**Comment by netapp-jani** [comment]
Thank you for your feedback. SRM is changed to VMware Live Site Recovery.
