### ISSUE TITLE
Spelling Error

### ISSUE THREAD

**Issue by SPGoetze** [NetAppDocs/ontap-tools-vmware-vsphere-10#22]
### Page URL

https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/concepts/ontap-tools-concepts-terms.html

### Page title

Key concepts and terms

### Summary

ONTAP tools Manager

ONTAP tools Manager provides more control to ONTAP tools for VMware vSphere administrator over the managed vCenter Server instances and onboarded storage backends. ONTAP tools Man**_a_**ger helps in management of vCenter Server instances, storage backends, certificates, passwords and log bundle downloads.

("Manger" -> "Manager")

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-jani** [comment]
@SPGoetze Thank you for your feedback. Typo is corrected now.
