### ISSUE TITLE
Link broken

### ISSUE THREAD

**Issue by ntap-johanneswagner** [NetAppDocs/ontap-tools-vmware-vsphere-10#28]
### Page URL

https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/deploy/prerequisites.html

### Page title

Prerequisites for deploying ONTAP tools for VMware vSphere

### Summary

The link in the Section "Refer to [Configuration limits to deploy ONTAP tools for VMware vSphere](https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/deploy/config-limits.html) for more details." returns a 404.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-jani** [comment]
@ntap-johanneswagner 
Thank you for contacting us with your feedback. After your inputs are researched internally, we will determine how best to address it and update the content at the earliest.

Thanks,
Jani

**Comment by netapp-jani** [comment]
@ntap-johanneswagner, the issue has been addressed. Thank you again for bringing this to our notice.
