### ISSUE TITLE
Not clear the SVM must be used if storage backend is associated in ONTAP Tools Manager

### ISSUE THREAD

**Issue by jpowellgit** [NetAppDocs/ontap-tools-vmware-vsphere-10#34]
### Page URL

https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/configure/add-storage-backend.html

### Page title

Add a storage backend

### Summary

If you associated a storage backend in ONTAP Tools Manager you are unable to do so in vCenter and will get an error.  If the storage backend has been associated in ONTAP Tools Manager then you can only add storage in vCenter using the SVM.   This is not clear and causes confusion.  Contact me at powej@netapp.com if more clarification is required.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-jani** [comment]
@jpowellgit 
Thank you for contacting us with your feedback. After your inputs are researched internally, we will determine how best to address it and update the content at the earliest.

Thanks,
Jani

**Comment by netapp-jani** [comment]
@jpowellgit Note added to [Add a storage backend](https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/configure/add-storage-backend.html) page. If you have further comments, please raise an internal doc [JIRA](https://jira.ngage.netapp.com/projects/OTVDOC/summary).
