### ISSUE TITLE
Documention needs a page to describe each and every option of the installation whether it is Single or HA 

### ISSUE THREAD

**Issue by pbNetApp** [NetAppDocs/ontap-tools-vmware-vsphere-10#35]
### Page URL

https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/deploy/ontap-tools-deployment.html

### Page title

Deploy ONTAP tools for VMware vSphere

### Summary

Customers and support is confused as to why some of the options in the install are available and if they are required to proceed with the installation. 

For example: Node Interconnect IP address on a Single-Node Installation, why is this needed for a single node install? This is one of the examples. Also, why isn't VP and SRA stated as optional and showing to add username/password if they only want to use for VSC? 

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-jani** [comment]
@pbNetApp 
Thank you for contacting us with your feedback. After your inputs are researched internally, we will determine how best to address it and update the content at the earliest.

Thanks,
Jani

**Comment by netapp-jani** [comment]
@pbNetApp, the UI is enhanced with description. If you still think doc needs to be updated, please raise a [JIRA](https://jira.ngage.netapp.com/projects/OTVDOC/summary) and we can discuss this with the engineering team internally.
