### ISSUE TITLE
Log in as the cluster or SVM user.

### ISSUE THREAD

**Issue by maboerue** [NetAppDocs/ontap-tools-vmware-vsphere-10#40]
### Page URL

https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/configure/configure-user-role-and-privileges.html

### Page title

Configure ONTAP user roles and privileges

### Summary

You wrote:
2. Access ONTAP System Manager using the cluster management IP address of the cluster.
3. Log in as the cluster or SVM user.

AFAIK it's impossible to login to System Manager GUI with an SVM user.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-jani** [comment]
Thank you for bringing this to our notice. We have updated the steps. Hope this helps.

Thanks,
Jani
