### ISSUE TITLE
Link Dead

### ISSUE THREAD

**Issue by calvinwonghk** [NetAppDocs/ontap-tools-vmware-vsphere-10#5]
### Page URL

https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/qsg_10.html

### Page title

ONTAP tools for VMware vSphere Quick Start

### Summary

For more information see [Requirements for deploying the ONTAP tools](https://docs.netapp.com/us-en/deploy/concept_space_and_sizing_requirements_for_ontap_tools_for_vmware_vsphere.html)

 <<< this link is not working!

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-jani** [comment]
@calvinwonghk Thank you for contacting us with your feedback. After your inputs are researched internally, we will determine how best to address it and update the content at the earliest.

Thanks,
Jani

**Comment by netapp-jani** [comment]
@calvinwonghk, we have fixed the links, please validate: [ONTAP tools for VMware vSphere Quick Start](https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/deploy/qsg_10.html)
